import { Viewport } from "next"
import "./globals.scss"
import UseHeight from "@/utils/hooks/useHeight"
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}

export const viewport: Viewport = {
	initialScale: 1,
	width: "device-width",
}
export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ko">
			<body>
				<UseHeight />
				<div className="main_layout">{children}</div>
			</body>
		</html>
	)
}
