import AuthProvider from "@/lib/provider/AuthProvider"
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ko">
			<body>
				<AuthProvider>{children}</AuthProvider>
			</body>
		</html>
	)
}
