import { Viewport } from "next"
import "./globals.scss"
import useSWR, { SWRConfig } from "swr"
import UseHeight from "@/utils/hooks/useHeight"
import { SWRProvider } from "@/utils/provider/swr"
export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
}

export const viewport: Viewport = {
	initialScale: 1,
	width: "device-width",
}
export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="ko">
			<SWRProvider>
				<body>
					<UseHeight />
					<div className="main_layout">{children}</div>
				</body>
			</SWRProvider>
		</html>
	)
}
